name: "Run OpenTofu docs via pre-commit + reviewdog"
description: "Runs tofu_docs on a ref range and posts terraform-docs diff suggestions via reviewdog"
author: "leinardi"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  from-ref:
    description: "Base git ref (e.g., PR base SHA)"
    required: true
  to-ref:
    description: "Head git ref (e.g., PR head SHA)"
    required: true
  github-token:
    description: "GitHub token for reviewdog (usually secrets.GITHUB_TOKEN)"
    required: true
  terraform-docs-version:
    description: "terraform-docs version tag (e.g., v0.20.0)"
    required: false
    default: "v0.20.0"

outputs:
  exitcode:
    description: "Exit code returned by the tofu_docs pre-commit hook"
    value: ${{ steps.tofu_docs.outputs.exitcode }}

runs:
  using: "composite"
  steps:
    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install Python deps + pre-commit
      shell: bash
      run: |
        set -euo pipefail
        pip install --no-cache-dir pre-commit

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1

    - name: Install terraform-docs
      shell: bash
      env:
        TD_VERSION: ${{ inputs.terraform-docs-version }}
      run: |
        set -euo pipefail

        url="https://github.com/terraform-docs/terraform-docs/releases/download/${TD_VERSION}/terraform-docs-${TD_VERSION}-linux-amd64.tar.gz"
        tmpdir="$(mktemp -d)"
        curl -fsSL "$url" -o "$tmpdir/terraform-docs.tar.gz"
        tar -xzf "$tmpdir/terraform-docs.tar.gz" -C "$tmpdir"
        install -m 0755 "$tmpdir/terraform-docs" "$RUNNER_TEMP/terraform-docs"
        echo "$RUNNER_TEMP" >> "$GITHUB_PATH"

    - name: Setup reviewdog binary
      uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f
      with:
        reviewdog_version: latest

    - name: Run OpenTofu docs (tofu_docs hook)
      id: tofu_docs
      shell: bash
      run: |
        # Run the hook and capture exit code without failing the step
        set +e
        set -o pipefail

        pre-commit run tofu_docs \
          --from-ref "${{ inputs.from-ref }}" \
          --to-ref   "${{ inputs.to-ref }}"

        rc=$?
        echo "exitcode=$rc" >> "$GITHUB_OUTPUT"

        # Capture any doc changes as a diff
        git diff > tofu-docs.diff || true

        # Do not fail here; let reviewdog decide
        exit 0

    - name: Report OpenTofu docs suggestions via reviewdog
      if: steps.tofu_docs.outputs.exitcode != '0'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        reviewdog \
          -name="opentofu docs" \
          -f=diff \
          -f.diff.strip=1 \
          -reporter=github-pr-review \
          -filter-mode=nofilter < tofu-docs.diff

        # Fail the job if there were doc changes needed
        exit 1
